from typing import Optional, Literal, Dict, Any
from pydantic import BaseModel, Field

class RAGQueryRequest(BaseModel):
    """
    Input schema for a user query.
    """
    message: str = Field(..., min_length=1, description="The user's query or message")
    thread_id: Optional[str] = Field(None, description="Conversation thread or session identifier")

class ApprovalRequestInfo(BaseModel):
    """
    Metadata about a pending human-in-the-loop tool execution approval request.
    """
    request_id: str = Field(..., description="Unique request ID for the pending approval")
    tool_name: str = Field(..., description="Name of the tool that requires approval")
    arguments: Dict[str, Any] = Field(..., description="Arguments passed to the tool call")

class ApproveRequestPayload(BaseModel):
    """
    Request body payload for approving/denying a pending tool call.
    """
    thread_id: str = Field(..., description="Conversation thread or session identifier")
    request_id: str = Field(..., description="The ID of the pending approval request")
    approved: bool = Field(..., description="Whether to approve (True) or deny (False) the tool execution")

class RAGQueryResponse(BaseModel):
    """
    Output schema containing the agent response and session details.
    """
    response_text: str = Field(..., description="The response generated by the RAG agent")
    thread_id: str = Field(..., description="Conversation thread or session identifier used")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Execution metadata (e.g. settings applied, timings)")
    approval_request: Optional[ApprovalRequestInfo] = Field(None, description="Details of a pending tool call requiring human approval")

class AgentRunResult(BaseModel):
    """
    Internal execution result returned by the Agent Adapter.
    """
    response_text: str
    approval_request: Optional[ApprovalRequestInfo] = None

