from typing import Optional, Literal, Dict, Any
from pydantic import BaseModel, Field

class SearchConfigOverride(BaseModel):
    """
    Advanced configuration settings for Azure AI Search, configurable per query.
    """
    endpoint: Optional[str] = Field(None, description="Azure AI Search endpoint URL override")
    index_name: Optional[str] = Field(None, description="Azure AI Search index name override")
    api_key: Optional[str] = Field(None, description="Azure AI Search API Key override")
    mode: Optional[Literal["semantic", "agentic"]] = Field(None, description="Search execution mode: 'semantic' (hybrid/reranked) or 'agentic' (multi-hop)")
    top_k: Optional[int] = Field(None, ge=1, le=50, description="Number of source documents to retrieve")
    vector_field_name: Optional[str] = Field(None, description="Name of the vector field in the index")
    semantic_configuration_name: Optional[str] = Field(None, description="Name of the semantic configuration to use")
    context_prompt: Optional[str] = Field(None, description="Custom context instruction prompt for rendering results")
    model: Optional[str] = Field(None, description="Model deployment name for agentic/vectorization reasoning (e.g. gpt-4.1-mini-demo)")
    azure_openai_resource_url: Optional[str] = Field(None, description="Azure OpenAI resource URL for agentic mode knowledge base creation")
    azure_openai_api_key: Optional[str] = Field(None, description="Azure OpenAI API key for agentic mode")

class RAGQueryRequest(BaseModel):
    """
    Input schema for a user query.
    """
    message: str = Field(..., min_length=1, description="The user's query or message")
    thread_id: Optional[str] = Field(None, description="Conversation thread or session identifier")
    search_overrides: Optional[SearchConfigOverride] = Field(None, description="Dynamic, advanced search configuration overrides")

class ApprovalRequestInfo(BaseModel):
    """
    Metadata about a pending human-in-the-loop tool execution approval request.
    """
    request_id: str = Field(..., description="Unique request ID for the pending approval")
    tool_name: str = Field(..., description="Name of the tool that requires approval")
    arguments: Dict[str, Any] = Field(..., description="Arguments passed to the tool call")

class ApproveRequestPayload(BaseModel):
    """
    Request body payload for approving/denying a pending tool call.
    """
    thread_id: str = Field(..., description="Conversation thread or session identifier")
    request_id: str = Field(..., description="The ID of the pending approval request")
    approved: bool = Field(..., description="Whether to approve (True) or deny (False) the tool execution")

class RAGQueryResponse(BaseModel):
    """
    Output schema containing the agent response and session details.
    """
    response_text: str = Field(..., description="The response generated by the RAG agent")
    thread_id: str = Field(..., description="Conversation thread or session identifier used")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Execution metadata (e.g. settings applied, timings)")
    approval_request: Optional[ApprovalRequestInfo] = Field(None, description="Details of a pending tool call requiring human approval")

class AgentRunResult(BaseModel):
    """
    Internal execution result returned by the Agent Adapter.
    """
    response_text: str
    approval_request: Optional[ApprovalRequestInfo] = None

